# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ubc
author: SiEPIC

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: -1
  allow_errors: false
  # timeout: -1
  # execute_notebooks: force
  # execute_notebooks: "off"
  # exclude_patterns:
  #   - '*notebooks/devsim/01_pin_waveguide*'

latex:
  latex_engine: pdflatex # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true # use sphinx-jupyterbook-latex for pdf builds as default

# Add a bibtex file so that we can create citations

html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://github.com/gdsfactory/ubc

# Information about where the book exists on the web
repository:
  url: https://github.com/gdsfactory/ubc
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# launch_buttons:
#   notebook_interface: jupyterlab
#   colab_url: "https://colab.research.google.com"

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.autodoc.typehints"
    - "sphinx.ext.autosummary"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
    - "matplotlib.sphinxext.plot_directive"
    - "sphinxcontrib.autodoc_pydantic"
  config:
    #autodoc_typehints: description
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    autodoc_typehints: description
    autodoc_typehints_format: short
    python_use_unqualified_type_names: True
    autodoc_type_aliases:
      "ComponentFactory": "ComponentFactory"
      "ComponentSpec": "ComponentSpec"
      "CrossSectionFactory": "CrossSectionFactory"
      "CrossSectionSpec": "CrossSectionSpec"
      "LayerSpec": "LayerSpec"
      "LayerSpecs": "LayerSpecs"
      "Layer": "Layer"
      "Layers": "Layers"
      "PathType": "PathType"
      "SDict": "sax.SDict"
      "sax.SDict": "sax.SDict"
      "gdsfactory.typings.ComponentFactory": "ComponentFactory"
      "gdsfactory.typings.ComponentSpec": "ComponentSpec"
      "gdsfactory.typings.CrossSectionFactory": "CrossSectionFactory"
      "gdsfactory.typings.CrossSectionSpec": "CrossSectionSpec"
      "gdsfactory.typings.LayerSpec": "LayerSpec"
      "gdsfactory.typings.LayerSpecs": "LayerSpecs"
      "gdsfactory.typings.Layer": "Layer"
      "gdsfactory.typings.Layers": "Layers"
      "gdsfactory.typings.PathType": "PathType"
      "CrossSection | str | dict[str, Any] | Callable[[...], CrossSection] | SymmetricalCrossSection | DCrossSection": "CrossSectionSpec"
      "Component | ComponentAllAngle | str | dict[str, Any] | Callable[[...], Component]": "ComponentSpec"
    nb_execution_raise_on_error: true
