[project]
docs_dir = "."
nav = [
  {"Home" = "index.md"},
  {"Reference" = [
    {"Components" = "components.md"},
    {"Components Plot" = "components_plot.md"},
    {"Changelog" = "changelog.md"}
  ]},
  {"Tutorial" = [
    {"Data Analysis" = "data_analysis.md"},
    {"Simulations" = "simulations.md"}
  ]}
]
site_dir = "_build/html"
site_name = "ubcpdk pdk"
site_url = "https://gdsfactory.github.io/ubc"

[project.plugins.autorefs]

[project.plugins.mkdocstrings]

[project.plugins.mkdocstrings.handlers.python]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_root_toc_entry = false
show_source = false

[project.plugins.search]

[project.theme]
name = "material"
