name: Code Security

on:
  pull_request:
  merge_group:
    branches: [main]
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          version: 0.12.17
      - name: Run Bandit
        run: uvx --from bandit==1.9.4 bandit -r ubcpdk -f txt --exit-zero

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          exit-code: "0"
          format: table
          scan-ref: .
          scan-type: fs
          scanners: vuln,misconfig,secret
