name: Build docs
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    uses: doplaydo/pdk-ci-workflow/.github/workflows/pages.yml@main
    secrets:
      GFP_API_KEY: ${{ secrets.GFP_API_KEY }}
      SIMCLOUD_APIKEY: ${{ secrets.SIMCLOUD_APIKEY }}
  deploy-docs:
    needs: docs
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
  deploy-s3:
    needs: docs
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Download pages artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: github-pages
          path: artifact-tmp
      - name: Extract docs
        run: |
          mkdir -p docs-html
          tar -xf artifact-tmp/artifact.tar -C docs-html
      - name: Deploy docs to S3
        uses: doplaydo/infra/.github/actions/deploy-docs-s3@main
        with:
          docs-path: docs-html/
          s3-prefix: ubc/
