name: Test Sample Projects
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  test-sample-projects:
    uses: doplaydo/pdk-ci-workflow-public/.github/workflows/test-sample-projects.yml@main
    secrets:
      GFP_API_KEY: ${{ secrets.GFP_API_KEY }}
