name: Update Badges
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  badges:
    uses: doplaydo/pdk-ci-workflow/.github/workflows/update_badges.yml@main
    secrets: inherit
